### ISSUE TITLE
Support Zookeeper based lock for carbon metada files parallel update

### ISSUE THREAD

**Issue by gvramana** [HuaweiBigData/carbondata#110]
Use Zookeeper to write lock carbon metadata parallel updates
Interface CarbonLock
LocalFileBasedLock, HDFSBasedLock, ZookeeperBasedLock should be derived from CarbonLock
CarbonLockFactory.GetLock() can create and give required lock on configuration basis.

spark.deploy.zookeeper.url is used in spark, based on that we can configure, carbon zookeeper property
Should unlock if locking client is killed.

Use cases:
1) write lock carbon metadata parallel updates.
2) Lock Dictionary files update during global key generation.

**Comment by sraghunandan** [comment]
closing as handled as part of #109
