### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by jackylk** [HuaweiBigData/carbondata#13]
Before any functional code refactory, we should do code clean up and make our build process in a decent way

I would go with following steps, please comment:

- [x] Clean up all commented code without modifying code logic. 
Molap-Aggregation - ?
Molap-Core - Ravindra
Molap-Data-Processor - Ravindra
Molap-Engine - Ravindra
Molap-Interface - Likun
Molap-Logging-Service - Likun
Molap-Spark-Interface  - Likun

- [x] Add the scalastyle check in maven and pass the check - LIkun

- [x] Add test case support in maven and pass the test - Ravindra

- [ ] Discuss the Java coding style and format all java code - Chenliang

- [x] Add fat jar support in maven and can be used in spark-shell and IDE for debugging. - CaiQiang

After these steps, we can continue to do functional refactory like renaming packages/class, abstracting interfaces.

 I will start working on the first task.
 **Anyone who picks task please reply on this issue for letting others know.**

**Comment by sraghunandan** [comment]
all the tasks have been handled.I will close this issue
