### ISSUE TITLE
Describe and Describe formatted is not working & Complex type children parsing logic need to update as per new changes

### ISSUE THREAD

**Issue by nareshpr** [HuaweiBigData/carbondata#187]
1) Describe command & describe formatted command is fixed to show primitive and complex data types
2) Changed Children parsing based on new list of child Dimension under parent dimension.
3) Added Number of child dims count as per child count into schema thrift
3) Fixed bug in CarbonTable

**Comment by sraghunandan** [comment]
Fixed with PR #188
