### ISSUE TITLE
different rules between java-code-format-template.xml and javastyle-config.xml 

### ISSUE THREAD

**Issue by eason-lyx** [HuaweiBigData/carbondata#36]
in javastyle-config.xml :    

> 
       <module name="Indentation">
            <property name="basicOffset" value="4"/>
            <property name="braceAdjustment" value="0"/>
            <property name="caseIndent" value="4"/>
            <property name="throwsIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
            <property name="arrayInitIndent" value="4"/>
        </module>
        ...
> 

in java-code-format-template.xml :
      

>
       <setting id="org.eclipse.jdt.core.formatter.indentation.size" value="2"/>
       ...
> 

this is different rules between java-code-format-template.xml and javastyle-config.xml 

we need to make it same.

**Comment by sraghunandan** [comment]
rules are synchronized
