### ISSUE TITLE
Support DataRetention Feature

### ISSUE THREAD

**Issue by ManoharVanam** [HuaweiBigData/carbondata#366]
If you have loaded wrong/duplicate/unwanted data into table & want to delete unwanted segments (loads), you can delete the segments using load StartTime/ load id.

Delete by load ID:
 Each load will have unique id associated with it. Using load id(s) , you can remove the load(s)

Example: Delete load 1,2,3 from table tableName
Here tableName is the name of your table & after executing the above command load 1,2,3 will be deleted 

Delete by segment LoadStartTime:
Each load will have LoadStartTime.  you can delete the load(s) based on specific LoadStartTime range command

Example:  DELETE SEGMENTS FROM TABLE TABLENAME where STARTTIME before '2016-05-10 00:00:00'

After executing the above command all segments status, with STARTTIME < 2016-05-10 00:00:00, will be updated as "Marked for Delete" & these segment(s) will not be considered for queries .

**Comment by gvramana** [comment]
Merged PR #367
