### ISSUE TITLE
[BUG][Create Table]Dictionary include/exclued column in not in table, but the table can still be created successfully

### ISSUE THREAD

**Issue by Zhangshunyu** [HuaweiBigData/carbondata#405]
for example:
`cc.sql("create table  zw_d4 (imei string,deviceInformationId string,mac string,productdate timestamp,updatetime timestamp,gamePointId double,contractNumber double) STORED BY 'org.apache.carbondata.format'  TBLPROPERTIES ('DICTIONARY_EXCLUDE'='aaa')").show`

`cc.sql("create table  zw_d4 (imei string,deviceInformationId string,mac string,productdate timestamp,updatetime timestamp,gamePointId double,contractNumber double) STORED BY 'org.apache.carbondata.format'  TBLPROPERTIES ('DICTIONARY_INCLUDE'='aaa')").show`
the column "aaa" int not in table "zw_d4", but the command can be executed successfully with no error.

**Comment by chenliang613** [comment]
@QiangCai  please check this issue.

**Comment by QiangCai** [comment]
same with [issue415](https://github.com/HuaweiBigData/carbondata/issues/415)
@Zhangshunyu you can close this issuse.
