### ISSUE TITLE
data load is failing with empty dimension column

### ISSUE THREAD

**Issue by mohammadshahidkhan** [HuaweiBigData/carbondata#476]
data load is failing with empty dimension column

**Comment by eason-lyx** [comment]
hi shahid, i think we are raise the same [issue.](https://github.com/HuaweiBigData/carbondata/issues/474)
empty dimension can work,but with exclude_dictionary,if the number of exclude_dictionary + the number of empty dimension >row size,data load will failure.
i have raise a pr to fix this,please check: 
#475

**Comment by mohammadshahidkhan** [comment]
Agree, closing issue #476 duplicate of #475

**Comment by mohammadshahidkhan** [comment]
Reopening the issue as the data load will fail if the (columns in a row)  > 
meta.memberMapping.length + meta.noDictionaryCols.length; 
and the some of dimension is having empty values.

Data:
ID,date,country,name,phonetype,serialname,salary,as,ds
1,2015/7/23,,aaa1,phone197,ASD69643,15000,,
2,2015/7/24,,aaa2,phone756,ASD42892,15001,,

Query:
           CREATE TABLE IF NOT EXISTS t3
           (ID Int, date Timestamp, country String,
           name String, phonetype String, serialname String, salary Int)
           STORED BY 'org.apache.carbondata.format' TBLPROPERTIES('DICTIONARY_EXCLUDE'='country')

LOAD DATA LOCAL INPATH 'csv file path' into table t3

**Comment by eason-lyx** [comment]
you are giving a data mismatch to the table structure u created.

**Comment by mohammadshahidkhan** [comment]
Closing this issue will be fixed with PR #475
