### ISSUE TITLE
LOAD DDL could not use keywords of carbon's datatype to define a table name, which is incompatible with HIVE.

### ISSUE THREAD

**Issue by Zhangshunyu** [HuaweiBigData/carbondata#581]
For example:
`create table _timestamp_ (imei string,AMSize string,channelsId string,ActiveCountry string, Activecity string,gamePointId double,deviceInformationId double,productionDate Timestamp,deliveryDate timestamp,deliverycharge double) STORED BY 'org.apache.carbondata.format'TBLPROPERTIES('DICTIONARY_INCLUDE'='gamePointId,deviceInformationId');

LOAD DATA INPATH 'hdfs://hacluster/Raghu/vardhandaterestruct.csv' INTO TABLE _timestamp_ OPTIONS('DELIMITER'=',', 'QUOTECHAR'= '"', 'FILEHEADER'= 'imei,deviceInformationId,AMSize,channelsId,ActiveCountry,Activecity,gamePointId,productionDate,deliveryDate,deliverycharge');

Error: org.apache.spark.sql.AnalysisException: missing EOF at 'OPTIONS' near 'timestamp'; line 1 pos 87 (state=,code=0)

`
timetamp is a keyword, and if the table name is a keyword, it would be parsed failure.

**Comment by foryou2030** [comment]
Another question, if we create a table with name "table_03" and load data with name "Table_03", load failed.  This is because carbon is case sensitive. But hive is case insensitive.
Shall we keep the same with hive?

@gvramana @kumarvishal09 @QiangCai pls check.

**Comment by Zhangshunyu** [comment]
#597

**Comment by Zhangshunyu** [comment]
#704 
this pr fix this issue.
