### ISSUE TITLE
Select Avg(StringType)+IntType cause stage failure

### ISSUE THREAD

**Issue by Jay357089** [HuaweiBigData/carbondata#635]
when execute "Select Avg(StringType)+IntType from table", it will cause unresolved exception and stage failure. i will raise a pr to handle this.

**Comment by gvramana** [comment]
What is the behaviour in case of hive

**Comment by Jay357089** [comment]
@gvramana hive shows "null".

**Comment by Jay357089** [comment]
handled. close it.
