### ISSUE TITLE
Update CarbonFile to support Federation

### ISSUE THREAD

**Issue by Hexiaoqiao** [HuaweiBigData/carbondata#644]
1. CanbonFile not support HDFS [Federation](http://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/Federation.html) currently, if given hdfs file location as "viewfs://master/tmp", it will throw Exception when load data into table.
2. Federation framework is widely used by more and more company, so it's necessary to support Federation.
I will offer a pr to handle this.

**Comment by chenliang613** [comment]
Looks good.
Look forward to seeing your pr.

**Comment by Hexiaoqiao** [comment]
it will be helpful with your supports.
i think HDFSCarbonFile has achieved completely to support Federation except being incompatible with schema `viewfs`. so update `HDFSCarbonFile` or add new Class `ViewFSCarbonFile`(?) implements `CarbonFile` will handle this.
actually i implement lite edition by update `HDFSCarbonFile` and it looks work well.

**Comment by ravipesala** [comment]
@Hexiaoqiao I guess it is better to add new class and any duplicate code between `HDFSCarbonFile` and 'ViewFSCarbonFile' can be moved to abstract class.

**Comment by Hexiaoqiao** [comment]
@chenliang613 @ravipesala pls review and offer me some tips if there are any unreasonable or wrong code.
