### ISSUE TITLE
Stream line procedure: Adding a new feature/defect in CarbonData opensource 

### ISSUE THREAD

**Issue by gvramana** [HuaweiBigData/carbondata#71]
[ Raising new Issue]
1) Raise a new issue, for each feature/defect 
-  keep it logical for review and merge across versions
-  preferably a functional, but design level also ok, explaining the purpose and impact of functionality .
2) Write description with necessary expectation from that issue.
- Expected interfaces 
- example references

[Update issue]
1) Please comment on issue.
2) If too much conflict, can discuss offline and update discussion outcome (to save time)
3) Any design/reverse engineered class diagram

[Raise new PR]
1) If Initial/Partial code changes required review(work in progress), Raise PR for with [WIP] after the  issue no. Like interfaces to be reviewed.
2) few commit suggestions
- For modified files, please do the style check of code at last and check in style check changes separate commit, other wise difficult to review changes.
- check in logical changes into separate commits and try to keep PR small.
- However use update last commit option while check in if last commit reason still holds good for current change, so that commits will not increase to too many.

[PR comments]
1) Please mention mandatory reviewers while raising using "@id" after build is success
2) reviewer can comment LGTM if Looks Good To Me, if OK.
3) If general comments w.r.t class, please mention at one place at class declaration, other wise give at specific line.

Please post your comments and we will consolidate our procedures to Wiki [How-to-contribute-and-Code-Style] once finalized.

**Comment by sraghunandan** [comment]
closing this as it is tracked in wiki how to contribute
