### ISSUE TITLE
DataLoading And query execution with ColumnGroup and DictionaryExclude

### ISSUE THREAD

**Issue by ashokblend** [HuaweiBigData/carbondata#728]
Because of reason below, one to one mapping is disturbed because of which Encoding is not written properly while data loading and also query execution have problem.
1. Dictionary exclude doesn't participate in mdkeygeneration
2. Number of dimension is written in one chunk

**Comment by chenliang613** [comment]
From now on, please report issues at JIRA : https://issues.apache.org/jira/browse/CARBONDATA/

**Comment by ashokblend** [comment]
It's handled as per https://github.com/HuaweiBigData/carbondata/pull/713
