### ISSUE TITLE
Describe formatted command for Timestamp data type

### ISSUE THREAD

**Issue by ashokblend** [HuaweiBigData/carbondata#730]
Timestamp datatype is showing as Dictionary as output of 
Describe formatted <tablename> command.

Need to change it to KEY_COLUMN as like NO Dictionary column

**Comment by chenliang613** [comment]
From now on, please report issues at JIRA : https://issues.apache.org/jira/browse/CARBONDATA/

**Comment by ashokblend** [comment]
this is handled as per https://github.com/HuaweiBigData/carbondata/pull/731
