### ISSUE TITLE
Recheck Calculation of dictiionaryFile existence

### ISSUE THREAD

**Issue by ashokblend** [HuaweiBigData/carbondata#746]
In some case dictionary file will not be available in Metadata folder
Hence for those scenario we need to check on filesystem if it exists

**Comment by chenliang613** [comment]
From now on, please report issues at JIRA : https://issues.apache.org/jira/browse/CARBONDATA/

**Comment by ashokblend** [comment]
It's handled with pr https://github.com/HuaweiBigData/carbondata/pull/641
